### ISSUE TITLE
How to add custom config such as schema.xml

### ISSUE THREAD

**Issue by dfurber** [dokku/dokku-solr#9]
The pre-build hook will copy /solr/schema.xml and /solr/solrconfig.xml into the solr container. But the README says nothing about this. I am glad to do this, but wonder along the way if we might also have a folder such as /solrconfig, and have it copy every file in that folder into the same folder. For other files like protwords.txt. My use case is running sunspot with Rails.

**Comment by josegonzalez** [comment]
Sure! I don't know much about solr, so I'll leave the best practices up to you :)

**Comment by cwant** [comment]
Just trying to follow along here ... where do you need to put the config so that it's put in the solr container?
I see from the commit it mentions `${TMPDIR}`, but I'm not sure where that is on the system in which I run `dokku solr:create ...` (is it the current directory? or in /tmp ... actually, I've tried both and they don't seem to copy the config into the container).

**Comment by josegonzalez** [comment]
Make a "solr" directory in your app and commit your config there. On the next deploy, we will extract the config and use that to configure solr.

**Comment by cwant** [comment]
Thanks for this. Is there a trigger needed to make solr re-extract the config after deploy? (like a post-deploy hook on the app or something?)
My app does have a `solr` dir, but I'm not seeing the `solr` containter getting re-built, and the config doesn't change in the container.
For reference, my app is called `training` the solr service is called `training-solr`, and I have:
```
$ dokku solr:links training-solr
training

$ dokku solr:app-links training
training-solr
```
But after pushing the app with git, I have a new web container, but the solr container is still old, e.g.,
```
$ sudo docker ps
CONTAINER ID   IMAGE                       COMMAND                  CREATED         STATUS         PORTS      NAMES
3e95774559e5   dokku/training:latest       "docker/entrypoint.s…"   8 minutes ago   Up 8 minutes   3000/tcp   training.web.1
76aa824fd6e9   solr:9.3.0                  "docker-entrypoint.s…"   22 hours ago    Up 22 hours    8983/tcp   dokku.solr.training-solr
```
I appreciate any insight you have about this (and apologies for being so clueless here).

**Comment by josegonzalez** [comment]
The config is moved into place but the container isn't restarted. Are you seeing that the config isn't in place?

**Comment by cwant** [comment]
Thanks Jose, I don't see the config getting moved into place (I think I will nuke what I have so far and rebuild to make sure I haven't broken something while trying things out).

The specific app I'm trying to Dokku-ize is this one:

https://github.com/ElixirTeSS/TeSS/tree/master/solr/conf

I'm not sure if having a `conf` directory in the `solr` directory is causing the issue, or if it's something else.

The Dokku version I am using is `0.27.8` (from Ubuntu 22.04 LTS), so maybe that's the issue.

Cheers,
Chris

**Comment by josegonzalez** [comment]
It needs to be directly in the solr directory, not in a conf subdirectory.

**Comment by cwant** [comment]
Okay thanks. I will adapt here.
I'll just mention that a lot of projects use the `solr/conf` subdirectory:

https://github.com/samvera/hyku/tree/main/solr/conf
https://github.com/ualbertalib/jupiter/tree/master/solr/conf
https://github.com/ElixirTeSS/TeSS/tree/master/solr/conf

(Maybe this is a `rails` thing? Or a libraries thing?)

**Comment by josegonzalez** [comment]
I don't know how those projects integrate with solr, but its almost certainly something custom since there isnt anything common about the other contents of the `solr` dir. Probably just project-specific.
